### ISSUE TITLE
Revisit naming

### ISSUE THREAD

**Issue by vdice** [brigadecore/brigade-github-app#30]
Consider revisiting naming of this project (as well as its corresponding [chart](https://github.com/Azure/brigade-charts/tree/master/charts/brigade-github-app) and associated documentation in [Brigade](https://github.com/Azure/brigade) to clarify/emphasize that this is a Github App-based gateway for Brigade.

**Comment by krancour** [comment]
Closing due to staleness, but please do reopen if necessary.

Also, this was taken into consideration for the Brigade v2-compatible replacement for this gateway, which is now named "brigade-github-gateway."
