### ISSUE TITLE
Environment parity with GitHub Actions

### ISSUE THREAD

**Issue by radu-matei** [brigadecore/brigade-github-app#35]
GitHub Actions injects [the following variables](https://developer.github.com/actions/creating-github-actions/accessing-the-runtime-environment/#environment-variables) into the environment executing an action.

Ideally, we would inject the same (exception might make `GITHUB_TOKEN`), so container images can be interchangeably used between Brigade and GitHub Actions.

Below is the full list of injected values:

Environment variable | Description
-- | --
HOME | The path to the GitHub home directory used to store user data. Value: /github/home.
GITHUB_WORKFLOW | The name of the workflow.
GITHUB_ACTION | The name of the action.
GITHUB_ACTOR | The name of the person or app that initiated the workflow. For example, octocat.
GITHUB_REPOSITORY | The owner and repository name. For example, octocat/Hello-World.
GITHUB_EVENT_NAME | The webhook name of the event that triggered the workflow.
GITHUB_EVENT_PATH | The path to a file that contains the payload of the event that triggered the workflow. Value: /github/workflow/event.json.
GITHUB_WORKSPACE | The GitHub workspace path. Value: /github/workspace. Note: GitHub actions must be run by the default Docker user (root). Ensure your Dockerfile does not set the USER instruction, otherwise you will not be able to access GITHUB_WORKSPACE.
GITHUB_SHA | The commit SHA that triggered the workflow.
GITHUB_REF | The branch or tag ref that triggered the workflow. For example, refs/heads/feature-branch-1. If neither a branch or tag is available for the event type, the variable will not exist.
GITHUB_TOKEN | A GitHub App installation token scoped to the repository containing  the workflow file. To access this environment variable from an action,  you must add the GITHUB_TOKEN secret to each action that  requires access. This variable is not available to an action by default.  To learn more about GitHub Action secrets, see "Storing secrets."

**Comment by ldrrp** [comment]
Is this related to this issue:

```
- Your workflow file was invalid: .github/workflows/blank.yml (Line: 49, Col: 12): Unrecognized named-value: 'GITHUB_ACTOR'. Located at position 1 within expression: GITHUB_ACTOR
```

**Comment by radu-matei** [comment]
Are you running Brigade and trying to use GitHub Actions workflows, @ldrrp ?

**Comment by Bharathkumarraju** [comment]
I am also facing the same issue?

**Comment by Bharathkumarraju** [comment]
```      - name: Dockerized the application
        run: export APP_TAG=$(echo $APP_TAG | cut -c1-7) && docker build -t samplepython:$APP_TAG .
        env:
          APP_TAG: ${{ GITHUB_SHA }}```

**Comment by radu-matei** [comment]
Not exactly sure what you're trying to achieve - could you please provide a bit more context, and ideally, a `brigade.js` file?

Thanks!

**Comment by bregenspan** [comment]
I think https://github.com/brigadecore/brigade/pull/259 is related? It's a fix for a different issue but seems like it could solve this as well.

**Comment by krancour** [comment]
Closing due to staleness, but please do reopen if necessary.
