### ISSUE TITLE
Check Run container errors when env var exceeds size limit

### ISSUE THREAD

**Issue by vdice** [brigadecore/brigade-github-app#36]
It appears there are cases where the check run utility will fail to run (and thus, fail to update a check run's status) if one or more of the values passed to it via [environment variables](https://github.com/Azure/brigade-github-app/blob/master/cmd/check-run/main.go#L20-L27) exceeds the default env var length limit (depending on Unix env).  When this occurs, the process then exits with `standard_init_linux.go:178: exec user process caused "argument list too long"` (Research seems to point to exceeding the env var length limit when searching on this error message.)

I've encountered this behavior when attempting to update a check run with the lengthy output of a test run -- so, `text`, or `CHECK_TEXT` is quite large; in fact, too large.

Assuming I'm correct as to the underlying cause of the issue, what might be an improvement we can make to avoid this limitation?  Perhaps adding the ability to mount a volume for pulling data of large sizes into this utility/container so it can then successfully make the GH check run api call?

**Comment by technosophos** [comment]
Yeah, mounting a volume would be easy enough to do. I think we could check for the env var, and if not present check a known location on the fs (or vice versa) so as to keep backward compat.

**Comment by technosophos** [comment]
Might be able to just change this:

https://github.com/brigadecore/brigade-github-app/blob/master/cmd/check-run/main.go#L24

And add a `envFileOr(VAR, PATH, DEFAULT)` method

**Comment by krancour** [comment]
Closing due to staleness, but please do reopen if necessary.
