### ISSUE TITLE
Multiple GitHub webhooks create worker pods in cluster

### ISSUE THREAD

**Issue by radu-matei** [brigadecore/brigade-github-app#37]
Using this as part of the CI process -- it is mainly used for the `pull_request` or `check_suite:requested` events. But as Brigade is executing the check run, and posting information about the build back to GitHub, it gets multiple webhooks -- the following builds are for a single PR:

```
$ brig build list --namespace brigade
ID                        	TYPE                   	PROVIDER   	PROJECT                                                       	STATUS   	AGE
01d64bmcj8a0df42r0bq87ywfk	check_suite:completed  	github     	brigade-4cf8fe2e2a0fe809cfe9bbbee83dcfbe9ff8d86c274145276d442c	Succeeded	17m
01d64bmcj53rjbqd2ed6fzxrqr	check_run:created      	github     	brigade-4cf8fe2e2a0fe809cfe9bbbee83dcfbe9ff8d86c274145276d442c	Succeeded	17m
01d64bmch5qb9q9evhwbart2h1	check_run:completed    	github     	brigade-4cf8fe2e2a0fe809cfe9bbbee83dcfbe9ff8d86c274145276d442c	Succeeded	17m
01d64bhcw299mhxna867gnndch	check_run:created      	github     	brigade-4cf8fe2e2a0fe809cfe9bbbee83dcfbe9ff8d86c274145276d442c	Succeeded	19m
01d64bgm1hh49yx9s5c37z1np9	check_suite:rerequested	github     	brigade-4cf8fe2e2a0fe809cfe9bbbee83dcfbe9ff8d86c274145276d442c	Succeeded	17m
01d64bgk8c95nfvrkgcz8fnxr0	pull_request           	github     	brigade-4cf8fe2e2a0fe809cfe9bbbee83dcfbe9ff8d86c274145276d442c	Succeeded	19m
```

This translates in multiple workers being created in my cluster:

```
$ kubectl get pods
NAME                                                    READY   STATUS      RESTARTS   AGE
brigade-worker-01d64bgk8c95nfvrkgcz8fnxr0               0/1     Completed   0          25m
brigade-worker-01d64bgm1hh49yx9s5c37z1np9               0/1     Completed   0          25m
brigade-worker-01d64bhcw299mhxna867gnndch               0/1     Completed   0          24m
brigade-worker-01d64bmch5qb9q9evhwbart2h1               0/1     Completed   0          23m
brigade-worker-01d64bmcj53rjbqd2ed6fzxrqr               0/1     Completed   0          23m
brigade-worker-01d64bmcj8a0df42r0bq87ywfk               0/1     Completed   0          23m
end-run-01d64bgm1hh49yx9s5c37z1np9                      0/1     Completed   0          23m
rust-build-01d64bgm1hh49yx9s5c37z1np9                   0/1     Completed   0          24m
start-run-01d64bgm1hh49yx9s5c37z1np9                    0/1     Completed   0          24m
```

And while the actual jobs for my project are only created once, multiple worker pods are created.

I'm curious how other projects handle this, and what are the GitHub webhook settings associated with the installation.

cc @vdice

**Comment by vdice** [comment]
Yea, these occur for other projects as well.

I believe we should be able to safely ignore handling `check_suite:completed/created` and `check_run:completed/created` to prevent spawning no-op brigade-worker pods..

**Comment by mumoshu** [comment]
@vdice Agreed. Are you ok if I implemented what @radu-matei has suggested in [his comment](https://github.com/brigadecore/brigade-github-app/pull/52#issuecomment-492600918)?

>  an optional list of per-project events that the controller would check before actually creating the worker pod.

I would add a new flag `--events` that is used like `--events check_suite:completed,check_suite:created,check_run:completed,check_run:completed,check_run:created` for this.

I've also considered implementing `include-events` for opting-in events to be processed, and `exclude-events` for opt-out as an alternative. But it turns out just too much effort for the goal, given any configuration possible with the two flags seems achievable with `--events` only.

And the flag name looks consistent with [`--authors`](https://github.com/brigadecore/brigade-github-app/blob/b6aab55ae38e61a5129c0e56c42dc773dad8d5b7/cmd/github-gateway/server.go#L40) as both being one plural noun :)

**Comment by vdice** [comment]
@mumoshu if we only use `--events`, what is the default behavior?  Events listed will be included/opt-in or excluded/opt-out?

Otherwise, the general approach seems great!

**Comment by mumoshu** [comment]
@vdice Thanks! Good point - I have three options for now:

1.  an empty string which means "everything"
2. `*` which means "everything"
3. `check_run,check_run:*,check_suite,check_suite:*,commit_comment,commit_comment:*,create,deployment,deployment_status,issue_comment,issue_comment:*,pull_request,pull_request:*,pull_request_review,pull_request_review:*,push,release,release:*,status` where `*` matches everything
   - I wanted to avoid `check_run` translated to `check_run,check_run:*` assuming there would be use-cases that the user wants to trigger broad `check_run` events only

I like 2 most. 3 seems ok but seems harder to maintain and explain. I like 1 least, as the semantics of the empty string meaining "everything" isn't intuitive.

Implementation-wise, I'd like to avoid introducing an another go pkg dependency just for globbing for 2 and 3. So probably `*` won't be an actual glob - it will be just a placeholder that can be placed after `:` to make the implementation as simple as possible.

WDYT?

**Comment by vdice** [comment]
@mumoshu If we go the route of opt-in, yes, it makes sense to support:

- `*` for everything
- a list of events (and/or event:action pairs) to watch, e.g. `check_run,pull_request:opened` etc.  Here, I don't know if it is necessary to support `*` for any action.  I would think if only the event is specified (`check_run`), we would default to opting in to all sub-actions under that event.  However, if a particular event:action is supplied (`pull_request:opened`), we'd only add that specific pair.  Though, not sure if this would be tricky to implement...

At a high level, I'm still leaning towards the default setup of all event:action pairs being handled.  Perhaps this can be done with the proposal above (default in chart and/or configuration elsewhere would be `*`) and only if the user supplied a list of events (again, via chart values, etc.), then this would override the default. What do you think?

**Comment by mumoshu** [comment]
@vdice Thanks for the feedback!

These make sense to me as well. The implementation will probably be simpler, which is nice.

> I'm still leaning towards the default setup of all event:action pairs being handled. 

So am I

> (default in chart and/or configuration elsewhere would be *) and only if the user supplied a list of events (again, via chart values, etc.), then this would override the default. What do you think?

Sounds good 👍

I'll give it a try to implement it and hopefully submit a PR soon.

**Comment by mumoshu** [comment]
Submitted #74.

I'll update the chart one it gets merged.
