### ISSUE TITLE
Improve error reporting

### ISSUE THREAD

**Issue by mumoshu** [brigadecore/brigade-github-app#73]
This is very similar to https://github.com/brigadecore/brigade/issues/938 but specific to brigade-github-app.

I think brigade-github-app should have an out-of-box way to tell the user what's went wrong when an init-container failed, in a more user-friendly way.

# Problem

Let's say you wrote a `brigade.js` that reacts on `issue_comment` on PRs. Commenting on a PR with `/whatever` results in brigade-github-app receiving a GitHub webhook and creating brigade-worker to run your `brigade.js`.

Now, when the init container failed while cloning the git repo due to permission issue, you have no easy way to debug what went wrong. `/whatever` doesn't trigger expected github checks, hence no PR statuses updated, no brigade workers run.

You can author your `brigade.js` to comment-back to the PR but it obviously don't work when the init container was failed - as brigade-worker has failed before running `brigade.js`.

# Possible Solution

How about `brigade-github-app` comment-back a message like `brigade-worker failed: <last N lines of failed (init) container of the brigade worker>`, if the triggering webhook is `issue_comment` on a github pull request, or `push` to a pull-requested branch?

This way the user can easily get what went wrong when, as soon as they push a new commit to a pull-requested branch, or add a comment on the pr?

**Comment by vdice** [comment]
Hmm, interesting thought.  I think enabling this comment-back functionality would be useful for both the sad case (as mentioned above, where something fails along the way) and the happy case (say, a comment-back with a simple message stating the intended action has run or is running successfully, which removes any doubts that actions might not have been triggered).

As long as the contents of the comment are ensured to not leak any sensitive/secret information (would have to refresh my memory on what is logged on an init container failure, etc.) then I think this could be a good way to go.

**Comment by mumoshu** [comment]
> As long as the contents of the comment are ensured to not leak any sensitive/secret information 

@vdice Good point!

Reading your comment, I got to think that making any assumption on what is/should be logged here is bad as whether it's safe or not depends two things:

- The init-container image the user has chosen
- We brigade developers never leak sensitive info to our default init-container logs

Instead, how about making each comment-back message include some instruction on obtaining logs from the failed build and nothing else?

> brigade-worker failed in init: run `brig build logs <FAILED BUILD ID>` to see what went wrong

Then we can implement https://github.com/brigadecore/brigade/issues/938 to finally address this feature request.

**Comment by vdice** [comment]
> Instead, how about making each comment-back message include some instruction on obtaining logs from the failed build and nothing else?

Agreed, I think this is a great way to go.

**Comment by krancour** [comment]
Closing due to staleness, but please do reopen if necessary.
