### ISSUE TITLE
Proposal: supress certain events from untrusted users until a trusted user approves

### ISSUE THREAD

**Issue by krancour** [brigadecore/brigade-github-app#75]
There have been a few different discussions in different threads about closing down an attack vector wherein untrusted users can open malicious PRs and Brigade will blindly trigger a build. This could be used, for instance, to steal credentials or abuse project resources.

Some discussion has involved restricting untrusted users from modifying `brigade.js`, but it's widely agreed upon now that that doesn't go far enough because if we don't also restrict the ability to modify other "executable somethings" (scripts, make targets, etc.) that build jobs rely upon, then the attack vector in question hasn't really been closed off.

After much discussion in https://github.com/brigadecore/brigade/issues/961, a more effective approach has been identified. This issue supercedes that one and moves further discussion of that approach to the appropriate repository.

## Current State

When a PR is opened or amended, commented upon, etc., a `pull_request` (with some `action` field in the payload further qualifying the event) is sent from Github to the gw. The gw _emits_ these events into Brigade _and_ if enabled, performs "check suite forwarding," which involves an API call to Github itself to prompt Github itself to send a `check_suite` event with an `action` of `rerequested` to the gw. The gateway also emits this into Brigade.

## Proposed Future State

__Note:__ To preserve backward compatibility, it is proposed that all of the following be hidden behind a feature flag.

When a PR is opened or amended, commented upon, etc., a `pull_request` (with some `action` field in the payload further qualifying the event) is sent from Github to the gw. If the event in question was triggered by a trusted user, everything happens the same as it does today. If the event was triggered by an untrusted user _and is one that commonly triggers a build_ (e.g. `pull_request` events with an `action` of `closed` do not typically trigger builds), then that event is _suppressed_-- i.e. not emitted into Brigade.

When an `issue_comment` event is subsequently received _from a trusted user_ and contains `/test` in its body, this is interpreted as a _one-time_ approval to test the PR in its current state. (i.e. future amendments to the PR require new approvals). This will prompt the "check suite forwarding" process that was previously bypassed.

### Caveat

Under this proposal, certain events from untrusted users, e.g. `pull_request` with `action` of `opened` will _never_ make it through the gateway and out into Brigade itself. This means this workflow is only suitable for installations of  Brigade (and project ` brigade.js` files) that trigger builds off of `check_suite` events rather than `pull_request` events). This is _already_ the common way of doing things, so this caveat doesn't seem damning to me.

**Comment by vdice** [comment]
I like this approach.  However, I may be missing something, because I believe we already have this functionality as of https://github.com/brigadecore/brigade-github-app/pull/56.  In short, this added emittance of `issue_comment` events from the gateway and hence enables `brigade.js` authors to add `issue_comment` event handlers, for kicking off jobs (the standard Check suite, in the most common case) based on comment text (`/brig run` has become the standard).  There is logic to not populate the webhook with actionable data if the comment does not come from a trusted user.  The most common case is, indeed, to one-time trigger build/test runs on PRs from un-trusted users (as the same logic we're familiar with remains: Brigade doesn't run by default from these PRs) -- but it can equally be used to (re-)trigger build/test runs on _any_ PR.

This approach gives each brigade.js author the flexibility to define what happens when a given comment comes in.  Perhaps the difference between what exists today and what this ticket mentions is a proposal to add stock comment handling/actions in this GH App code itself?

**Comment by krancour** [comment]
> This approach gives each brigade.js author the flexibility to define what happens when a given comment comes in.

But the problem is that if logic in `brigade.js` is all that stands between a malicious PR author and execution of their nefarious scheme, they can just undo those protections in the `brigade.js` and they're off to the races.

If we build some protection into the gw itself, we shut down that avenue of attack.

**Comment by krancour** [comment]
@vdice this:

> as the same logic we're familiar with remains: Brigade doesn't run by default from these PRs

I forgot about this. You're right.

https://github.com/brigadecore/charts/blob/master/charts/brigade-github-app/values.yaml#L40-L43

Now I'm wondering why discussion of this attack vector has come up a few times in multiple threads.

**Comment by krancour** [comment]
@vdice I am still thinking we should do this, even if Brigade already doesn't (by default) trigger builds from PRs by untrusted users. Here's why...

You've don a great job showing how _trusted_ users can approve/trigger a build with a `/brig run` comment. In each of those cases, however, the `brigade.js` was modified to enable that behavior. If this is going to be a frequently-desired behavior, we should consider having good support for it so that users don't need to implement this pattern in their `brigade.js` themselves.

That would seem to make this a good candidate for inclusion in the utils project, and iirc, that is something we've already discussed. But I wonder if even that doesn't go far enough. Not to turn this into a Drake discussion, but consider brigdrake as an example of a custom worker that actually doesn't act on `brigade.js` and drives the build off of some _other_ kind of model (`Drakefile.yaml`). All these _other_ types of workers would still benefit from this pattern of not triggering builds from untrusted users until a truster user approves....

And that brings me back to feeling we should build this into the gateway. After all-- isn't it a _gateway's_ responsibility to emit (or not emit) events into Brigade?

Any thoughts on this?

**Comment by vdice** [comment]
Fair points; perhaps it would be useful to build it into the gateway for the reasons you've mentioned.

However, I'm still unclear as to the usefulness of updating the gateway to not emit PR events associated with untrusted users.  Even though the gateway today emits them, protection exists in Brigade to not run CI for them (after checking the `allowedAuthors` list).  Is the intention to move that safety check further back a level?  It would still reference `allowedAuthors` in doing so, right?  Hence, the issue would still remain that if the `allowedAuthors` setup is lax (to allow all/most), then the change feels moot.  Most likely I'm just not apprehending the full impact of the proposed change, so if you could clarify a bit, I'd be grateful.

**Comment by krancour** [comment]
> However, I'm still unclear as to the usefulness of updating the gateway to not emit PR events associated with untrusted users. Even though the gateway today emits them, protection exists in Brigade to not run CI for them (after checking the allowedAuthors list).

By "allowedAuthors" do you mean `allowedAuthorRoles`?

I think you're right that the "suppression half" of this proposal is basically already the way things work. Perhaps then, we can further refine this proposal to _only_ involve adding support for `/brig run` comments directly to the gateway?

**Comment by vdice** [comment]
> By "allowedAuthors" do you mean allowedAuthorRoles?

Oops, indeed!

I agree, adding handling/logic for a standard `/brig run` comment in the gateway itself would add value (remove necessity for `brigade.js` authors to write or use utils logic for this, and add support for workers that don't use `brigade.js`).  👍

**Comment by krancour** [comment]
@vdice I love it when we put our heads together and realize a great feature requires a smaller change than I had thought. 😄

**Comment by krancour** [comment]
Closing due to staleness.

Also, everything from this discussion was factored into the new Brigade v2-compatible GitHub gateway, which has retained the ability to define the author associations who are allowed to automatically have things run. It has also, as suggested by this thread, implemented handling of `brig /run` or `brig /check` comments so that individual Brigade users do not have to handle those in userland.
