### ISSUE TITLE
Add instructions for ingress controller

### ISSUE THREAD

**Issue by sbussard** [brigadecore/brigade-github-app#91]
Please add instructions for use with ingress controllers so as not to incur the extra expense of an additional load balancer

**Comment by krancour** [comment]
This is really just a matter of tweaking a few settings in the `values.yaml` when doing `helm install` or `helm upgrade`.

I'm not saying no to this by any means, but given that ingress is a widely understood topic that is pretty generically a k8s concern (i.e. not a Brigade-specific one) and given that Brigade's approach to enabling ingress via Helm is pretty conventional as far as Helm charts go, adding docs on this won't be a priority.

**Comment by krancour** [comment]
Contributions welcome.

**Comment by krancour** [comment]
Closing due to staleness, but please do reopen if necessary.
