### ISSUE TITLE
Scope GH App access token properly

### ISSUE THREAD

**Issue by vdice** [brigadecore/brigade-github-app#97]
With the latest version of the [go-github](https://github.com/google/go-github) dependency (bumped in https://github.com/brigadecore/brigade-github-app/pull/95) comes the ability to scope a requested access token to a per-repo basis, along with finer-grain permission levels.  See https://developer.github.com/v3/apps/#create-an-installation-access-token-for-an-app

Minimally, we should scope down to the repo attached to the inbound event from GH.  Worth exploring other options as well.

**Comment by krancour** [comment]
Closing due to staleness, but please do reopen if necessary.
